# Checkov configuration for blog portfolio infrastructure
# This file defines security scanning rules and exceptions for compliance

# Framework to run
framework:
  - terraform

# Skip checks that are not applicable or acceptable for this project
skip-check:
  # S3 bucket versioning - enabled where needed
  - CKV_AWS_21
  
  # S3 bucket logging - not required for this use case
  - CKV_AWS_18
  
  # S3 bucket MFA delete - not required for dev environment
  - CKV_AWS_17
  
  # RDS backup retention - configured appropriately per environment
  - CKV_AWS_133
  
  # RDS deletion protection - disabled for dev, enabled for prod
  - CKV_AWS_129
  
  # CloudFront WAF - optional feature flag controlled
  - CKV_AWS_68
  
  # ALB access logs - not required for this use case
  - CKV_AWS_91
  
  # ECS task definition memory limit - configured appropriately
  - CKV_AWS_34

# Download external modules
download-external-modules: true

# Evaluate variables
evaluate-variables: true