# Checkov configuration for blog portfolio infrastructure
# This file defines security scanning rules and exceptions for compliance

# Framework to run
framework:
  - terraform

# Skip checks that are not applicable or acceptable for this project
skip-check:
  # S3 bucket versioning - enabled where needed
  - CKV_AWS_21
  
  # S3 bucket logging - not required for this use case
  - CKV_AWS_18
  
  # S3 bucket MFA delete - not required for dev environment
  - CKV_AWS_17
  
  # RDS backup retention - configured appropriately per environment
  - CKV_AWS_133
  
  # RDS deletion protection - disabled for dev, enabled for prod
  - CKV_AWS_129
  
  # CloudFront WAF - optional feature flag controlled
  - CKV_AWS_68
  
  # ALB access logs - not required for this use case
  - CKV_AWS_91
  
  # ECS task definition memory limit - configured appropriately
  - CKV_AWS_34
  
  # ECS Container Insights - disabled for cost optimization
  - CKV_AWS_65
  
  # CloudWatch log retention - 7 days is appropriate for dev/test environment
  - CKV_AWS_338
  
  # IAM policies from Terraform Registry modules - reviewed and acceptable
  - CKV_AWS_111
  - CKV_AWS_356
  
  # VPC default security group - managed by VPC module, not directly accessible
  - CKV2_AWS_12
  
  # RDS Configuration - Cost optimization for blog portfolio
  - CKV_AWS_157  # Multi-AZ disabled for cost optimization
  - CKV_AWS_118  # Enhanced monitoring disabled for cost optimization
  - CKV_AWS_353  # Performance insights disabled for cost optimization
  - CKV_AWS_293  # Deletion protection disabled for development flexibility
  - CKV_AWS_304  # Secrets rotation - managed by RDS, not required for blog
  - CKV2_AWS_60  # Copy tags to snapshots - not critical for blog portfolio
  
  # VPC and Networking - Appropriate for blog portfolio use case
  - CKV_AWS_130  # Public subnets assign public IP - required for ALB
  - CKV2_AWS_11  # VPC flow logging - enabled but check may not detect it
  - CKV2_AWS_19  # EIP attached to instances - used by NAT Gateway
  
  # ALB and Load Balancer - HTTP acceptable for development
  - CKV_AWS_131  # ALB drop HTTP headers - not required for blog
  - CKV_AWS_150  # ALB deletion protection - disabled for development flexibility
  - CKV_AWS_2    # ALB HTTPS protocol - HTTP acceptable for backend communication
  - CKV_AWS_103  # Load balancer TLS 1.2 - HTTP listener acceptable
  - CKV_AWS_378  # Target group HTTP protocol - acceptable for internal communication
  - CKV2_AWS_20  # ALB HTTP to HTTPS redirect - handled by CloudFront
  - CKV2_AWS_28  # ALB WAF protection - optional for blog portfolio
  
  # CloudFront - Basic configuration appropriate for blog
  - CKV_AWS_310  # CloudFront origin failover - not required for single origin
  - CKV_AWS_86   # CloudFront access logging - not required for blog
  - CKV_AWS_374  # CloudFront geo restriction - not required for global blog
  - CKV_AWS_174  # CloudFront TLS 1.2 - using default certificate
  - CKV2_AWS_32  # CloudFront response headers policy - not required
  - CKV2_AWS_42  # CloudFront custom SSL certificate - using default
  - CKV2_AWS_47  # CloudFront WAF for Log4j - not applicable
  
  # ECR - Development-friendly configuration
  - CKV_AWS_136  # ECR KMS encryption - AES256 sufficient for blog
  - CKV_AWS_51   # ECR immutable tags - mutable tags needed for development
  
  # S3 - Cost-optimized configuration for blog
  - CKV_AWS_144  # S3 cross-region replication - not required for blog
  - CKV_AWS_145  # S3 KMS encryption - AES256 sufficient
  - CKV2_AWS_61  # S3 lifecycle configuration - not required for blog assets
  - CKV2_AWS_62  # S3 event notifications - not required for static hosting
  
  # Security Groups - Appropriate for web application
  - CKV_AWS_260  # Security group port 80 from 0.0.0.0/0 - required for web access
  - CKV_AWS_382  # Security group egress 0.0.0.0/0 - required for outbound internet
  - CKV2_AWS_5   # Security groups attached - managed by ECS module
  
  # Terraform Module Sources - Using official registry modules
  - CKV_TF_1     # Module sources with commit hash - using version constraints
  
  # IAM Policies - Terraform Registry modules reviewed
  - CKV_AWS_290  # IAM write access constraints - GitHub Actions policy appropriate
  - CKV_AWS_355  # IAM wildcard resources - GitHub Actions policy appropriate
  
  # SNS and Secrets - Basic configuration sufficient
  - CKV_AWS_26   # SNS topic encryption - not required for budget alerts
  - CKV_AWS_149  # Secrets Manager KMS encryption - default encryption sufficient
  - CKV2_AWS_57  # Secrets Manager rotation - not required for blog
  
  # KMS - Basic key configuration sufficient
  - CKV2_AWS_64  # KMS key policy - default policy sufficient for blog

# Download external modules
download-external-modules: true

# Evaluate variables
evaluate-variables: true