name: Infrastructure Security Scanning

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-deploy.yml'
  pull_request:
    branches: [main]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-deploy.yml'

jobs:
  # Security Scanning
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          config_file: .checkov.yml
          output_format: sarif
          output_file_path: checkov.sarif
          download_external_modules: true
          quiet: true

      - name: Upload Security Scan Results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: checkov.sarif

  # Code Quality Check
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check

  # Cost Estimation (for PRs only)
  cost-estimation:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
        continue-on-error: true

      - name: Generate Cost Estimate
        run: |
          if [ -n "${{ secrets.INFRACOST_API_KEY }}" ]; then
            infracost breakdown --path=terraform \
              --terraform-var-file=terraform/environments/prod.tfvars \
              --format=json \
              --out-file=infracost.json
            
            infracost comment github --path=infracost.json \
              --repo=$GITHUB_REPOSITORY \
              --github-token=${{ github.token }} \
              --pull-request=${{ github.event.pull_request.number }} \
              --behavior=update
          else
            echo "💰 Cost estimation skipped - INFRACOST_API_KEY not configured"
            echo "To enable cost estimation, add INFRACOST_API_KEY to repository secrets"
          fi
        continue-on-error: true

  # Terraform Cloud Status Check
  terraform-cloud-status:
    runs-on: ubuntu-latest
    needs: [security-scan, code-quality]
    
    steps:
      - name: Terraform Cloud Integration Status
        run: |
          echo "✅ Security scan completed"
          echo "✅ Code quality check completed"
          echo "🚀 Terraform Cloud will handle infrastructure deployment"
          echo ""
          echo "📋 Terraform Cloud Workflow:"
          echo "  1. Detects changes in terraform/ directory"
          echo "  2. Automatically runs terraform init, validate, and plan"
          echo "  3. For main branch: applies changes automatically (if configured)"
          echo "  4. For PRs: shows plan in Terraform Cloud UI"
          echo ""
          echo "🔗 Check your Terraform Cloud workspace for deployment status:"
          echo "   https://app.terraform.io/app/blog-terraform/workspaces/blog-portfolio-infra"